server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    hostname: cloud-howei-admin

spring:
  application:
    name: cloud-howei-admin
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

