server:
  port: 8011

spring:
  application:
    name: cloud-howei-wa

eureka:
  instance:
    prefer-ip-address: true
    hostname: cloud-howei-wa
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    fetch-registry: true
    register-with-eureka: true