server:
  port: 8100
spring:
  application:
    name: cloud-howei-auth
  redis:
    host: localhost
    port: 6379
    password: 12345
  security:
    user:
      name: admin
      password: 123456
eureka:
  instance:
    hostname: cloud-howei-auth
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/


